import { Geist, Geist_Mono } from "next/font/google"; 
// Importa as fontes Geist e Geist_Mono direto do Google Fonts via Next.js

import "./globals.css";
// Importa o arquivo global de estilos

const geistSans = Geist({
  variable: "--font-geist-sans", // Cria uma variável CSS para usar a fonte
  subsets: ["latin"],            // Define que apenas o subset latino será usado
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // Cria uma variável CSS para a fonte monoespaçada
  subsets: ["latin"],
});

export const metadata = {
  title: "MackHub",                       // Título padrão da aplicação
  description: "Generated by create next app", // Descrição padrão
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">  {/* Define idioma da página para pt-br */}
      <head>
        {/* Importa o favicon do projeto */}
        <link rel="icon" href="./SVG.png" type="image/svg+xml" />
      </head>

      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Aplica as fontes e renderiza o conteúdo das páginas */}
        {children}
      </body>
    </html>
  );
}

